// <auto-generated />
using System;
using System.Collections.Generic;
using BlikonDrive.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlikonDrive.Infrastructure.Migrations
{
    [DbContext(typeof(DriveDbContext))]
    [Migration("20260528022808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlikonDrive.Core.Entities.DriveFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AzureBlobPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("azure_blob_path");

                    b.Property<string>("BlikonId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blikon_id");

                    b.Property<DateTime?>("ContentIndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("content_indexed_at");

                    b.Property<string>("ContentText")
                        .HasColumnType("text")
                        .HasColumnName("content_text");

                    b.Property<string>("CoreFolderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("core_folder_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Dictionary<string, object>>("Exif")
                        .HasColumnType("jsonb")
                        .HasColumnName("exif");

                    b.Property<DateTime?>("ExifExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exif_extracted_at");

                    b.Property<string>("Extension")
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upload_status");

                    b.HasKey("Id");

                    b.HasIndex("BlikonId")
                        .HasDatabaseName("idx_files_blikon_id");

                    b.HasIndex("CoreFolderId")
                        .HasDatabaseName("idx_files_core_folder");

                    b.HasIndex("DeletedAt")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("BlikonDrive.Core.Entities.FileComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlikonId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blikon_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("idx_comments_file_id");

                    b.ToTable("file_comments", (string)null);
                });

            modelBuilder.Entity("BlikonDrive.Core.Entities.FileComment", b =>
                {
                    b.HasOne("BlikonDrive.Core.Entities.DriveFile", "File")
                        .WithMany("Comments")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("BlikonDrive.Core.Entities.DriveFile", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
